### ISSUE TITLE
deleteFile at Mongodb not delete all chunks in database

### ISSUE THREAD

**Issue by Scott1984** [yii2tech/file-storage#11]
After add file into mongo, and delete it
"files" table will delete that one record
but "chunks" table will remain n-1 chunk records which takes unreleased space.

$deleteCount = $this->getCollection()->remove(['_id' => $document['_id']], ['limit' => 1]);
I try remove ['limit' => 1] from line 187 at Bucket, and it works fine

but I'm not sure if this is right things to do, thanks!

**Comment by klimov-paul** [comment]
Unable to reproduce. Following unit test passes correctly:

```php
class BucketTest extends TestCase
{
    use BucketTestTrait;

   // ...

    public function testDeleteFile()
    {
        $bucket = $this->createFileStorageBucket();
        $testBucketName = 'test_delete_file_bucket';
        $bucket->setName($testBucketName);

        $testFileName = 'test_file_name.tmp';
        $testFileContent = 'Test file content';
        $bucket->saveFileContent($testFileName, $testFileContent);

        $this->assertTrue($bucket->deleteFile($testFileName), 'Unable to delete file!');

        $this->assertEquals(0, $bucket->getCollection()->count());
        $this->assertEquals(0, $bucket->getCollection()->getFileCollection()->count());
    }
}
```

Behavior of the `Collection::remove()` is covered by unit test at `yii2-mongodb` as well:
https://github.com/yiisoft/yii2-mongodb/blob/master/tests/file/CollectionTest.php#L129-L151

Make sure you are using latest versions of both `yii2tech/file-storage` and `yiisoft/yii2-mongodb`

**Comment by Scott1984** [comment]
I'm using $bucket->copyFileIn( , ); put bigger files( like 1mb or 10mb) in , and it produce 1 file record and mutiple chunk records in mongo.
$bucket->deleteFile(); only delete "one file record" and "one chunk record", so the file is gone, but chunks will not all cleaned if the file is bigger than 1 chunk.

I'm using
Yii 2 File Storage 1.1.2
Yii Framework 2 mongodb 2.1.4
MongoDB server version: 3.4.7

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-mongodb/issues/227
