### ISSUE TITLE
Support of custom bucket name

### ISSUE THREAD

**Issue by Vladnev** [yii2tech/file-storage#13]
Hi, I have a need to split the bucket into subfolders, with different purposes, for match local directories.

To solve this problem, I see a good option to add support for the `name` field in the bucket configuration.

Or maybe there is a ready-made solution?

Example of needle config:

```php
    'storages' => [
        's3' => [
            'class' => 'yii2tech\filestorage\amazon\Storage',
            'buckets' => [
                'bucket_a' => [
                    'name' => 'aws_bucket_name',
                    'urlName' => 'aws_bucket_name/folder',
                ],
                'bucket_b' => [
                    'name' => 'aws_bucket_name',
                    'urlName' => 'aws_bucket_name/other_folder',
                ],
            ],
        ],
        'local' => [
            'class' => 'yii2tech\filestorage\local\Storage',
            'basePath' => Yii::getAlias('@storage'),
            'filePermission' => 0777,
            'buckets' => [
                'bucket_a' => [
                    'baseSubPath' => 'folder',
                ],
                'bucket_b' => [
                    'baseSubPath' => 'other_folder',
                ],
            ],
        ],
    ],
```

Solution:
**\yii2tech\filestorage\BaseStorage::getBucket**
```php
    public function getBucket($bucketName)
    {
        if (!array_key_exists($bucketName, $this->_buckets)) {
            throw new InvalidParamException("Bucket named '{$bucketName}' does not exists in the file storage '" . get_class($this) . "'");
        }
        $bucketData = $this->_buckets[$bucketName];
        if (is_object($bucketData)) {
            $bucketInstance = $bucketData;
        } else {
            $bucketData['name'] = isset($bucketData['name']) ? $bucketData['name'] : $bucketName;
            $bucketInstance = $this->createBucketInstance($bucketData);
            $this->_buckets[$bucketName] = $bucketInstance;
        }
        return $bucketInstance;
    }
```

What can you say about this?

**Comment by klimov-paul** [comment]
Sorry, but I do not understand what are you asking for.
Name of the Bucket is the your-program-level bucket ID, you can specify any name you want via key at the `Storage::$buckets`. If you are able to reuse same bucket with different 'url name' at S3 there is absolutely no need for any extra 'name' handling.

**Comment by Vladnev** [comment]
I will try to describe in more detail.
As I understand, the essence of filestoreage, is to give a complete abstraction over the file system. Imagine we have two categories of files(names can be duplicated):
 files_a,
 files_b 
for them there are two local folders, we configure them:
```php
'buckets' => [
                'files_a' => [
                    'baseSubPath' => 'files_a',
                ],
                'files_b' => [
                    'baseSubPath' => 'files_b',
                ],
            ],
```

We rake take them by:
```php
\Yii::$app->get('fileStorage')->getStorage('local')->getBucket('files_a')
```

And now we need these same two folders on the aws bucket, how we can get them changing only getStorage() parameter?
```php
\Yii::$app->get('fileStorage')->getStorage('s3')->getBucket('files_a')
```

**Comment by klimov-paul** [comment]
I still do not understand what is the problem. You may have achieve your goal using [Hub Storage](https://github.com/yii2tech/file-storage/blob/master/hub/Storage.php), although it make a little sense to operate several file storages expliciltly.

Using [Amazon Storage](https://github.com/yii2tech/file-storage/blob/master/amazon/Storage.php) you can refere same bucket several times with different sub folders using `Bucket::$fileSubDirTemplate`:

```php
'fileStorage' => [
            'class' => 'yii2tech\filestorage\amazon\Storage',
            'buckets' => [
                'bucket_a' => [
                    'urlName' => 'aws_bucket_name',
                    'fileSubDirTemplate' => 'folder'
                ],
                'bucket_b' => [
                    'urlName' => 'aws_bucket_name',
                    'fileSubDirTemplate' => 'other_folder'
                ],
            ],
        ],
```

**Comment by Vladnev** [comment]
Yes this is the solution that I was looking for.
I didn't take into account combining this parameters.
Thank.
