### ISSUE TITLE
What about different permission for directories and files?

### ISSUE THREAD

**Issue by MysteryDragon** [yii2tech/file-storage#14]
I'm talking about `yii2tech\filestorage\local\Storage::$filePermission`.
As I can see, this property is used both for directory and file creation. So, if I need 755 for directories, my files will also have 755 and that's why will be executable.
Why can't we set their own permissions?

Unfortunately the best expected name for such property will be exactly `filePermission`, and `dirPermission` fits good for directories. It will break compability...

But, perhaps, we can add `dirPermission` with `null` by default, and change behavior if it's not `null`? Also not so good solution, of course...

**Comment by klimov-paul** [comment]
Resolved by commit a7c4888ebebcf2f6c8c1d5e2931e4cf46e66c573
