### ISSUE TITLE
aws version 3

### ISSUE THREAD

**Issue by alex-volga** [yii2tech/file-storage#16]
Not work with aws-sdk-php ver 3

Class 'Aws\S3\Enum\CannedAcl' not found

**Comment by klimov-paul** [comment]
I am no longer have access to Amazon S3 environment. Thus I am unable to create any solution for it.
Even if pull request with such solution appears I will be unable to verify whether it is correct or not.
Either use older version of aws-sdk or create your own storage and bucket classes pair for new one or seek another file-storage library.
