### ISSUE TITLE
Make this package slim

### ISSUE THREAD

**Issue by hyuzea** [yii2tech/file-storage#20]
I and maybe anyone else people dont use all the storages provided here. I think storage extensions such mongodb, aws, hub, sftp should moved to its own repo, leave just the core and local storage extension instead. In fact I [done the job](/sup-ham/yii2-filestorage) for myself uses only and also created separated [extension for aliyun oss](/sup-ham/yii2-filestorage-aliyunoss)

**Comment by klimov-paul** [comment]
Rejected.

First of all, I can not see any problem having several storages under the same repo: it is a question of saving several kilobytes, which does not seem to worth the efforts.

Secondly, this package is almost out of support, I have no reason to spend extra time splitting the repository into several ones.
