### ISSUE TITLE
add minio 

### ISSUE THREAD

**Issue by des1roer** [yii2tech/file-storage#21]
### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.?.?
| Yii Framework Version | 2.0.?
| File Storage Type     | local/sftp/amazon/mongodb
| PHP version           | 
| Operating system      |

**Comment by klimov-paul** [comment]
Rejected.

This package is almost out of support, I have no reason to spend extra time adding any more storage implementations.
