### ISSUE TITLE
Scalability question

### ISSUE THREAD

**Issue by StalkAlex** [yii2tech/file-storage#3]
Is there any way to split this abstraction on different local servers?

**Comment by klimov-paul** [comment]
I am unsure I understand what do you mean.

You may use `Hub` storage:
https://github.com/yii2tech/file-storage/blob/master/hub/Storage.php

It allows combine different storages, based on different platforms with different configurations under the single interface. With it you will be able to manipulate all bcukets as equal at the same program layer.

**Comment by StalkAlex** [comment]
I have two servers in local network, so I need to replicate all files from the main where web app is running. There should be ftp realisation in file linked above, but I can't find it in repository.

**Comment by klimov-paul** [comment]
Unfortunally there is no 'ftp' file storage implemented yet.
If someone creates a PR for it, it whould be great.

**Comment by klimov-paul** [comment]
See #6

**Comment by StalkAlex** [comment]
Hey, Paul! Thank you for the implementation
