### ISSUE TITLE
Suggestion for DownloadAction

### ISSUE THREAD

**Issue by vuongminh-xx** [yii2tech/file-storage#8]
Why we don't use `openFile` in bucket to get handler and pass it to `sendStreamAsFile` method in `response` for send file? It will flexible more option when download file we can detect send file inline or not and resolve a large file with `content-range`.

**Comment by klimov-paul** [comment]
If you are ready to work on implementation - send a PR for it.

**Comment by vuongminh-xx** [comment]
I'm ready. PR will be created soon.

**Comment by klimov-paul** [comment]
Resolved by commit 74240a87b760b8b4ecddd443d3fc0dbe3a5e8c5d
